spring:
  profiles:
    active: test
---
server:
  port: 8003
spring:
  profiles: test
  application:
    name: duohe-chat-api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #Nacos 链接地址
        namespace: a60273f4-07fb-4568-82eb-d078a3b02107 #Nacos 命名空间ID
      config:
        server-addr: 127.0.0.1:8848  #Nacos 链接地址
        namespace: a60273f4-07fb-4568-82eb-d078a3b02107 #Nacos 命名空间ID
        group: DEFAULT_GROUP  # 默认分组就是DEFAULT_GROUP，如果使用默认分组可以不配置
        file-extension: yml   #默认properties
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 #配置Sentinel dashboard地址
        port: 8719  #这个端口配置会在应用对应的机器上启动一个Http Server，该Server会与 Sentinel 控制台做交互
      datasource:
        flow:
          nacos:
            server-addr: 127.0.0.1:8848 #nacos的访问地址，，根据上面准备工作中启动的实例配置
            dataId: cloud-sentinel-flow-service #nacos中存储规则的dataId
            groupId: DEFAULT_GROUP #nacos中存储规则的groupId
            namespace: a60273f4-07fb-4568-82eb-d078a3b02107 #Nacos 命名空间的ID
            data-type: json #配置文件类型
            rule-type: flow #类型来自RuleType类 - 流控规则
        degrade:
          nacos:
            server-addr: 127.0.0.1:8848 #nacos的访问地址，，根据上面准备工作中启动的实例配置
            dataId: cloud-sentinel-degrade-service #nacos中存储规则的dataId
            groupId: DEFAULT_GROUP #nacos中存储规则的groupId
            namespace: a60273f4-07fb-4568-82eb-d078a3b02107 #Nacos 命名空间的ID
            data-type: json #配置文件类型
            rule-type: degrade #类型来自RuleType类 - 熔断规则
#spring:
  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password: aa666123
    timeout: 5000ms
dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    # 订阅服务提供方的应用列表，订阅多个服务提供者使用 "," 连接
    subscribed-services: duohe-chat-engine
rocketmq:
  name-server: 192.168.157.202:9876
  producer:
    # 小坑：必须指定group
    group: test-group
