spring:
  profiles:
    active: test #默认运行环境
---
server:
  port: 8001
spring:
  profiles: test  #运行环境 + 命名空间名称
  application:
    name: duohe-chat-engine   #唯一名称
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  #Nacos 链接地址
        namespace: a60273f4-07fb-4568-82eb-d078a3b02107 #Nacos 命名空间ID
      config:
        server-addr: 127.0.0.1:8848  #Nacos 链接地址
        namespace: a60273f4-07fb-4568-82eb-d078a3b02107 #Nacos 命名空间ID
        group: DEFAULT_GROUP  # 默认分组就是DEFAULT_GROUP，如果使用默认分组可以不配置
        file-extension: yml   #默认properties
#spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chat_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 30
      maxWait: 50000
mybatis:
  mapper-locations: classpath:mapper/*.xml

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.duohe.project.service
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
    host: 127.0.0.1
  registry:
    # 挂载到 Spring Cloud 的注册中心
    address: spring-cloud://localhost
rocketmq:
  name-server: 192.168.157.202:9876
  producer:
    # 小坑：必须指定group
    group: test-group

